version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: ".github/workflows/"
    cooldown:
      default-days: 7
    schedule:
      interval: "quarterly"
